development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cab_service_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cab_service_test

production:
  adapter: redis
  url: redis://redistogo:5cf128fe7c715bcaaf38197fbe8b2d1e@soldierfish.redistogo.com:9766/
  channel_prefix: cab_service_production
